# Generated by Django 5.2.7 on 2025-10-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='label',
            field=models.CharField(default='My Address', help_text="e.g. Home, Work, Parents' House", max_length=50),
        ),
    ]
