# Generated by Django 5.2.7 on 2025-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_useraddress_default_userprofile_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
