# Generated by Django 5.2.7 on 2025-10-13 21:54

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=custom_storages.MediaStorage(), upload_to='uploads/')),
            ],
        ),
    ]
